#!/bin/bash

# X3 Docker Entrypoint
# Reads x3.conf-dist, replaces all %VARIABLE% placeholders with environment
# variable values, and writes out x3.conf

BASECONFDIST=/x3/x3src/docker/x3.conf-dist
BASECONF=/x3/data/x3.conf

# Marker stamped as the first line of every conf THIS script generates.
# Regeneration policy:
#   - no x3.conf                -> generate (and stamp the marker)
#   - x3.conf with the marker   -> regenerate: env + template are the source
#                                  of truth, so config changes actually land
#                                  on restart instead of freezing at first
#                                  container start
#   - x3.conf without the marker -> user-managed (e.g. volume-mounted);
#                                  never touched
GENMARKER='// GENERATED BY dockerentrypoint.sh from x3.conf-dist. Do not hand-edit: this file is REGENERATED ON EVERY CONTAINER START while this marker is the first line. To manage x3.conf yourself, replace it with a file that lacks this marker.'

if [ -f "$BASECONF" ] && ! head -n 1 "$BASECONF" | grep -qF 'GENERATED BY dockerentrypoint.sh'; then
    echo "Found user-managed config at $BASECONF (no generation marker), leaving it alone"
else
    echo "Generating $BASECONF from template..."

    # Set defaults for required variables (can be overridden by environment)
    : "${X3_GENERAL_NAME:=x3.network}"
    : "${X3_GENERAL_BIND_ADDRESS:=127.0.0.1}"
    : "${X3_GENERAL_DESCRIPTION:=Network Services}"
    : "${X3_GENERAL_DOMAIN:=example.com}"
    : "${X3_GENERAL_NUMERIC:=199}"
    : "${X3_UPLINK_ADDRESS:=127.0.0.1}"
    : "${X3_UPLINK_PORT:=8888}"
    : "${X3_UPLINK_PASSWORD:=changeme}"

    # Server block
    # 8 = Nefarious 1.3.x; 9 = Nefarious 2.0.x (nefarious2) — must match your ircd.
    : "${X3_SERVER_TYPE:=8}"
    : "${X3_HIDDEN_HOST_TYPE:=1}"
    # MUST match the ircd's HOST_HIDING_KEY* F:lines; change in production —
    # stock keys make style-2 cloaks predictable.
    : "${X3_HIDDEN_HOST_KEY1:=45432}"
    : "${X3_HIDDEN_HOST_KEY2:=76934}"
    : "${X3_HIDDEN_HOST_KEY3:=98336}"
    : "${X3_HIDDEN_HOST_PREFIX:=NETWORK}"

    # OpServ clone-G-line threshold (untrusted_max).  Default 6 (stock).
    # 0 disables it — testbeds set X3_UNTRUSTED_MAX=0 in .env.local so harness
    # connection volume from a single host isn't auto-G-lined.
    : "${X3_UNTRUSTED_MAX:=6}"

    # OpServ / ChanServ / Global identity + limits
    : "${X3_OPSERV_NICK:=O3}"
    : "${X3_OPSERV_HOSTNAME:=X3.Services}"
    : "${X3_DEBUG_CHANNEL:=#TheOps}"
    : "${X3_ALERT_CHANNEL:=#TheOps}"
    : "${X3_STAFF_AUTH_CHANNEL:=#OperServ}"
    : "${X3_CLONE_GLINE_DURATION:=2h}"
    : "${X3_CHANSERV_NICK:=X3}"
    : "${X3_OFF_CHANNEL:=no}"
    : "${X3_MAX_OWNED:=2}"
    : "${X3_MAX_CHAN_USERS:=512}"
    # Value is a conf list body: each channel stays individually quoted.
    : "${X3_SUPPORT_CHANNEL:=\"#Operations\", \"#Help\"}"
    : "${X3_GLOBAL_NICK:=Global}"
    # Also used by the snoop module (templatized with the other modules).
    : "${X3_SNOOP_CHANNEL:=#MrSnoopy}"

    # Modules
    : "${X3_SOCKCHECK_MAX_SOCKETS:=0}"
    : "${X3_SOCKCHECK_GLINE_DURATION:=1d}"
    : "${X3_TRACK_CHANNEL:=#MrPeanuts}"
    : "${X3_MEMOSERV_BOT:=MemoServ}"
    : "${X3_MEMO_EXPIRY:=30d}"
    : "${X3_MEMO_LIMIT:=30}"
    # qserver: no shipped literal credential — generate a random password
    # when the deployment doesn't provide one.
    : "${X3_QSERVER_PASSWORD:=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 16)}"
    : "${X3_BLACKLIST_GLINE_DURATION:=1h}"

    # Mail — disabled by default: the image ships no MTA at
    # /usr/sbin/sendmail, so "enabled" only meant every cookie mail
    # failed at sendmail exec time.  Set X3_MAIL_ENABLE=1 (and a working
    # mailer or SMTP server) to turn it on.
    : "${X3_MAIL_ENABLE:=0}"
    : "${X3_MAIL_MAILER:=/usr/sbin/sendmail}"
    : "${X3_MAIL_SMTP_SERVER:=localhost}"
    : "${X3_MAIL_SMTP_SERVICE:=smtp}"

    # Databases
    : "${X3_DB_SAVE_FREQUENCY:=30m}"

    # NickServ (AuthServ) defaults
    : "${X3_NICKSERV_NICK:=AuthServ}"
    : "${X3_DEFAULT_MAXLOGINS:=3}"
    : "${X3_HARD_MAXLOGINS:=10}"
    : "${X3_AUTO_OPER:=+oxwgs}"
    : "${X3_AUTO_OPER_PRIVS:=CHAN_LIMIT SHOW_INVIS SHOW_ALL_INVIS KILL LOCAL_KILL REHASH RESTART DIE JUPE LOCAL_JUPE OPMODE WHOX SEE_CHAN PROPAGATE DISPLAY SEE_OPERS WIDE_GLINE FORCE_OPMODE REMOTEREHASH CHECK SEE_SECRET_CHAN WIDE_SHUN WIDE_ZLINE LIST_CHAN}"
    : "${X3_PASSWD_MIN_LENGTH:=4}"
    : "${X3_PASSWD_MIN_DIGITS:=0}"
    : "${X3_PASSWD_MIN_UPPER:=0}"
    : "${X3_PASSWD_MIN_LOWER:=0}"
    : "${X3_EMAIL_ENABLED:=0}"
    : "${X3_EMAIL_REQUIRED:=0}"
    : "${X3_COOKIE_TIMEOUT:=2d}"
    : "${X3_ACCOUNTS_PER_EMAIL:=1}"
    # Derived from X3_GENERAL_DOMAIN (set above) unless overridden.
    : "${X3_TITLEHOST_SUFFIX:=${X3_GENERAL_DOMAIN}}"

    # LDAP defaults (disabled unless overridden)
    : "${X3_LDAP_ENABLE:=0}"
    : "${X3_LDAP_WRITEBACK:=0}"
    : "${X3_LDAP_URI:=ldap://localhost:389}"
    : "${X3_LDAP_BASE:=ou=users,dc=example,dc=net}"
    : "${X3_LDAP_DN_FMT:=uid=%s,ou=users,dc=example,dc=net}"
    : "${X3_LDAP_ADMIN_DN:=cn=admin,dc=example,dc=net}"
    : "${X3_LDAP_ADMIN_PASS:=changeme}"
    : "${X3_LDAP_FIELD_ACCOUNT:=uid}"
    : "${X3_LDAP_FIELD_PASSWORD:=userPassword}"
    : "${X3_LDAP_FIELD_EMAIL:=mail}"
    : "${X3_LDAP_FIELD_OSLEVEL:=X3AccountLevel}"
    : "${X3_LDAP_FILTER:=(objectClass=inetOrgPerson)}"
    : "${X3_LDAP_AUTOCREATE:=1}"
    : "${X3_LDAP_TIMEOUT:=10}"

    # Substitute into a temp copy, then stamp the marker and move into
    # place, so a crash mid-generation never leaves a half-substituted
    # marker-less (= treated as user-managed) conf behind.
    GENTMP="$BASECONF.gen.$$"
    cp "$BASECONFDIST" "$GENTMP"

    # Find all %VARIABLE% placeholders in the config and substitute them
    # with corresponding environment variable values
    grep -oE '%[A-Za-z_][A-Za-z0-9_]*%' "$GENTMP" | sort -u | while read -r placeholder; do
        # Extract variable name (remove the % signs)
        varname="${placeholder:1:-1}"

        # Get the value from environment (indirect expansion)
        value="${!varname}"

        # Only substitute if the variable is set
        if [ -n "$value" ]; then
            # Escape for use as a sed replacement with '|' as the s///
            # delimiter: backslash FIRST (so the escapes we add next are not
            # themselves re-escaped), then '&' (whole-match backreference)
            # and the '|' delimiter itself.  '/' needs no escaping here.
            escaped_value=$(printf '%s\n' "$value" | sed -e 's/\\/\\\\/g' -e 's/&/\\&/g' -e 's/|/\\|/g')
            sed -i "s|${placeholder}|${escaped_value}|g" "$GENTMP"
        else
            echo "Warning: No value set for ${varname}, leaving ${placeholder} unchanged"
        fi
    done

    { printf '%s\n' "$GENMARKER"; cat "$GENTMP"; } > "$BASECONF"
    rm -f "$GENTMP"

    echo "Generated $BASECONF from template"
fi

# Run the command passed to docker (CMD from Dockerfile)
exec "$@"
